# Generated by Django 4.1.7 on 2023-04-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tel_duenio',
            field=models.CharField(max_length=30),
        ),
    ]
