# Generated by Django 4.1.7 on 2023-04-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_mascota_edad_alter_mascota_tel_duenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
