# Generated by Django 4.1.7 on 2023-04-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_mascota_nombre_alter_mascota_nombre_duenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(default='por_hacer', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
